export const ADD_REPO_SUCCESS = "ADD_REPO_SUCCESS";
export const ADD_REPO_ERROR = "ADD_REPO_ERROR";
export const LOAD_REPOS_SUCCESS = "LOAD_REPOS_SUCCESS";
export const LOAD_REPOS_ERROR = "LOAD_REPOS_ERROR";
export const SELECT_REPO_SUCCESS = "SELECT_REPO_SUCCESS";
export const SELECT_REPO_ERROR = "SELECT_REPO_ERROR";
